// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKMFUNte7HTb2-3cTZt49COkpEjTcEmQ0',
    appId: '1:860572583274:web:7f5215003cf03f5e169113',
    messagingSenderId: '860572583274',
    projectId: 'sandesh-app-72dc0',
    authDomain: 'sandesh-app-72dc0.firebaseapp.com',
    storageBucket: 'sandesh-app-72dc0.appspot.com',
    measurementId: 'G-SW2C6QWZ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_zzcwQirSrJB2eivv95jmfREj1Pbp9Gg',
    appId: '1:860572583274:android:10e3a018607db28e169113',
    messagingSenderId: '860572583274',
    projectId: 'sandesh-app-72dc0',
    storageBucket: 'sandesh-app-72dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzaw6-ErGF1cfGqlRjw9Py7IeRF_0VELM',
    appId: '1:860572583274:ios:89e2903f3a74a0e0169113',
    messagingSenderId: '860572583274',
    projectId: 'sandesh-app-72dc0',
    storageBucket: 'sandesh-app-72dc0.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );
}
